version: "3.8"

services:
  pgdb:
    image: postgres:14.1-alpine
    container_name: pgdb
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

  django:
    build: .
    container_name: django
    command: >
      sh -c "python3 ./server/manage.py migrate &&
             python3 ./server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - pgdb

volumes:
  pgdata: