# Generated by Django 4.2.19 on 2025-02-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=300, verbose_name='Отчетство')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Доход')),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Семейный доход')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CreditPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('loan_size', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Размер кредита')),
                ('period', models.IntegerField(verbose_name='Длительность в месяцах')),
                ('init_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Первоначальный взнос')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Комиссия за выдачу кредита')),
                ('early_repayment', models.BooleanField(default=False, verbose_name='Возможность досрочного погашения')),
                ('early_repayment_commission', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия за досрочное погашение')),
                ('use_family_income', models.BooleanField(default=False, verbose_name='Использовать семейный доход')),
            ],
            options={
                'verbose_name': 'Кредитная программа',
                'verbose_name_plural': 'Кредитные программы',
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_size', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Размер кредита')),
                ('period', models.IntegerField(verbose_name='Длительность в месяцах')),
                ('init_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Первоначальный взнос')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_credits', to='app.clients', verbose_name='Клиент')),
                ('credit_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_program_credits', to='app.creditprograms', verbose_name='Кредитная программа')),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_credits', to='app.clients', verbose_name='Поручитель')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DocTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документа',
            },
        ),
        migrations.CreateModel(
            name='IncomeProofTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название способа')),
            ],
            options={
                'verbose_name': 'Способ подтверждения дохода',
                'verbose_name_plural': 'Способы подтверждения дохода',
            },
        ),
        migrations.CreateModel(
            name='InsuranceObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект страхования')),
            ],
            options={
                'verbose_name': 'Объект страхования',
                'verbose_name_plural': 'Объекты страхования',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип страхования')),
            ],
            options={
                'verbose_name': 'Тип страхования',
                'verbose_name_plural': 'Типы страхования',
            },
        ),
        migrations.CreateModel(
            name='InsuranceVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страховая компания')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
            },
        ),
        migrations.CreateModel(
            name='PaymentChangeReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Причина изменения графика платежей')),
            ],
            options={
                'verbose_name': 'Причина изменения в графике платежей',
                'verbose_name_plural': 'Причины изменения в графике платежей',
            },
        ),
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название состояния платежа')),
            ],
            options={
                'verbose_name': 'Состояние платежа',
                'verbose_name_plural': 'Состояния платежей',
            },
        ),
        migrations.CreateModel(
            name='VehicleDealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название дилера')),
            ],
            options={
                'verbose_name': 'Название дилера',
                'verbose_name_plural': 'Названия дилеров',
            },
        ),
        migrations.CreateModel(
            name='VehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.CreateModel(
            name='VehicleStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название состояния авто')),
            ],
            options={
                'verbose_name': 'Состояние автомобиля',
                'verbose_name_plural': 'Состояния автомобиля',
            },
        ),
        migrations.CreateModel(
            name='SpecialConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название специального условия')),
                ('condition', models.CharField(max_length=300, verbose_name='Содержание спец условия')),
                ('credit_programm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_program_special_conditions', to='app.creditprograms', verbose_name='Кредитная программа')),
                ('insurance_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_vendor_special_conditions', to='app.insurancevendors', verbose_name='Страховая компания')),
                ('vehicle_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_dealer_special_conditions', to='app.vehicledealers', verbose_name='Автодилер')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_special_conditions', to='app.vehiclemodels', verbose_name='Модель Авто')),
            ],
            options={
                'verbose_name': 'Специальное условие',
                'verbose_name_plural': 'Специальные условия',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата платежа')),
                ('main_payment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Основной долг')),
                ('percents_payment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Процент на остаток')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_payment_schedules', to='app.paymentconditions', verbose_name='Состояние платежа')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payment_schedules', to='app.credits', verbose_name='Кредит')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_payment_schedules', to='app.paymentchangereasons', verbose_name='Причина изменения графика')),
            ],
            options={
                'verbose_name': 'График платежа',
                'verbose_name_plural': 'Графики платежей',
            },
        ),
        migrations.CreateModel(
            name='PaymentDelays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payment_delays', to='app.credits', verbose_name='Кредит')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_payment_delays', to='app.paymentschedules', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Просрочка по платежу',
                'verbose_name_plural': 'Просрочки по платежу',
            },
        ),
        migrations.CreateModel(
            name='PaymentCalculationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название способа')),
                ('credit_programm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_program_payment_calculation_types', to='app.creditprograms', verbose_name='Кредитная программа')),
            ],
            options={
                'verbose_name': 'Способ расчета ежемесячного платежа',
                'verbose_name_plural': 'Способы расчета ежемесячного платежа',
            },
        ),
        migrations.CreateModel(
            name='MandatoryInsurances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('credit_programm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_program_mandatory_insurances', to='app.creditprograms', verbose_name='Кредитная программа')),
                ('insurance_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_object_mandatory_insurances', to='app.insuranceobjects', verbose_name='Объект страхования')),
                ('insurance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_type_mandatory_insurances', to='app.insurancetypes', verbose_name='Тип страхования (обязательный/опциональный)')),
            ],
            options={
                'verbose_name': 'Обязательное страхование',
                'verbose_name_plural': 'Обязательные страхования',
            },
        ),
        migrations.CreateModel(
            name='MandatoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название обязательного документа')),
                ('credit_programm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_program_mandatory_docs', to='app.creditprograms', verbose_name='Кредитная программа')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_type_mandatory_docs', to='app.doctypes', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Обязательный документ',
                'verbose_name_plural': 'Обязательные документы',
            },
        ),
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('date_from', models.DateTimeField(verbose_name='Дата начала действия страхования')),
                ('date_to', models.DateTimeField(verbose_name='Дата окончания действия страхования')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_insurances', to='app.clients', verbose_name='Клиент')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_insurances', to='app.credits', verbose_name='Кредит')),
                ('insurance_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_insurances', to='app.insuranceobjects', verbose_name='Объект страхования')),
                ('insurance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_insurances', to='app.insurancetypes', verbose_name='Тип страхования')),
                ('insurance_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_insurances', to='app.insurancevendors', verbose_name='Страховая компания')),
            ],
            options={
                'verbose_name': 'Страхование',
                'verbose_name_plural': 'Страхование',
            },
        ),
        migrations.AddField(
            model_name='creditprograms',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_credit_programs', to='app.currencies', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='creditprograms',
            name='income_proof_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_proof_type_credit_programs', to='app.incomeprooftypes', verbose_name='Способ подтверждения дохода'),
        ),
        migrations.AddField(
            model_name='creditprograms',
            name='vehicle_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_state_credit_programs', to='app.vehiclestates', verbose_name='Состояние авто'),
        ),
        migrations.CreateModel(
            name='ClientsDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверено?')),
                ('change_date', models.DateField(auto_now=True, verbose_name='Дата изменения документа')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_documents', to='app.clients', verbose_name='Клиент')),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_type_documents', to='app.doctypes', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='BlackLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_black_lists', to='app.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Черный список',
                'verbose_name_plural': 'Черные списки',
            },
        ),
    ]
